twig:
    #default_path: '%kernel.project_dir%/documents'
    paths:
        '%kernel.project_dir%/templates': ~
        '%kernel.project_dir%/documents': 'templates'
    globals:
        timezone: '%timezone%'
        locale: '%locale%'
        currency: '%currency%'

when@test:
    twig:
        strict_variables: true
